---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~4.0
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: '"Halt updates for now"'
    flux.weave.works/locked_user: Stefan Prodan <stefan@weave.works>
spec:
  releaseName: redis
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: redis
    version: 4.2.10
  values:
    image:
      repository: bitnami/redis
      tag: 4.0.11
    service:
      type: ClusterIP
      port: 6379
    cluster:
      enabled: false
    usePassword: false
    master:
      persistence:
        enabled: false
